package Views;

import dao.mysql.AmbientesDAO;
import dao.mysql.ObjetoDAO;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import models.Ambiente;
import models.TabelaBase;

public class TelaAmbiente extends javax.swing.JDialog {

    private AmbientesDAO ambienteDao = null;
    private ObjetoDAO objetoDao = null;
    private int codigoSelecionadoAmb = 0;
    private int codigoSelecionadoObj = 0;
    private int codigoSelecionadoProj = 0;

    public TelaAmbiente(java.awt.Frame parent, boolean modal, int codigoSelecionadoAmb, int codigoSelecionadoProj) {
        super(parent, modal);
        initComponents();
        objetoDao = new ObjetoDAO();
        ambienteDao = new AmbientesDAO();
        this.codigoSelecionadoProj = codigoSelecionadoProj;
        this.codigoSelecionadoAmb = codigoSelecionadoAmb;
        if (codigoSelecionadoAmb != 0) {
            btnNovoObjeto.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNovoObjeto = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluirObjeto = new javax.swing.JButton();
        lblAmbiente = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        scrTabela = new javax.swing.JScrollPane();
        tblObjeto = new javax.swing.JTable();
        btnEditarObjeto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnNovoObjeto.setText("Novo");
        btnNovoObjeto.setEnabled(false);
        btnNovoObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoObjetoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar ");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluirObjeto.setText("Excluir");
        btnExcluirObjeto.setEnabled(false);
        btnExcluirObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirObjetoActionPerformed(evt);
            }
        });

        lblAmbiente.setText("Cadastro de Ambiente");

        jLabel1.setText("Descrição");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblObjeto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblObjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblObjetoMouseClicked(evt);
            }
        });
        scrTabela.setViewportView(tblObjeto);

        btnEditarObjeto.setText("Editar");
        btnEditarObjeto.setActionCommand("Editar");
        btnEditarObjeto.setEnabled(false);
        btnEditarObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarObjetoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnExcluirObjeto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditarObjeto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNovoObjeto))
                            .addComponent(scrTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAmbiente)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(19, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAmbiente)
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoObjeto)
                    .addComponent(btnExcluirObjeto)
                    .addComponent(btnEditarObjeto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(416, 385));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoObjetoActionPerformed
       AbrirTelaObjetoNovo();
    }//GEN-LAST:event_btnNovoObjetoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        SalvarAmbiente();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        CarregarTelaAmbiente();
    }//GEN-LAST:event_formWindowActivated

    private void tblObjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblObjetoMouseClicked
        JTable tabela = (JTable) evt.getSource();
        int row = tabela.rowAtPoint(evt.getPoint());

        String codigo = tabela.getModel().getValueAt(row, 0) + "";
        
        codigoSelecionadoObj = Integer.parseInt(codigo);
        
        btnExcluirObjeto.setEnabled(true);
        btnEditarObjeto.setEnabled(true);
    }//GEN-LAST:event_tblObjetoMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        AtualizaTabelaObjeto();
    }//GEN-LAST:event_formWindowOpened

    private void btnExcluirObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirObjetoActionPerformed
        ExcluirObjeto();
    }//GEN-LAST:event_btnExcluirObjetoActionPerformed

    private void btnEditarObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarObjetoActionPerformed
        AbrirTelaObjetoEditar();
    }//GEN-LAST:event_btnEditarObjetoActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAmbiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAmbiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAmbiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAmbiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaAmbiente dialog = new TelaAmbiente(new javax.swing.JFrame(), true, 0, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditarObjeto;
    private javax.swing.JButton btnExcluirObjeto;
    private javax.swing.JButton btnNovoObjeto;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAmbiente;
    private javax.swing.JScrollPane scrTabela;
    private javax.swing.JTable tblObjeto;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables


    private void CarregarTelaAmbiente() {
        if (codigoSelecionadoAmb > 0) {
            Ambiente amb = ambienteDao.SelecionarPorId(codigoSelecionadoAmb);
            txtDescricao.setText(amb.getDescricao());
        }
    }
    
    private void AbrirTelaObjetoNovo(){
        TelaObjeto telaObjeto = new TelaObjeto(null, true, codigoSelecionadoAmb, 0);
        telaObjeto.setVisible(true);
        
        AtualizaTabelaObjeto();
    }
    
    private void AbrirTelaObjetoEditar(){
        TelaObjeto telaObjeto = new TelaObjeto(null, true, codigoSelecionadoAmb, this.codigoSelecionadoObj);
        telaObjeto.setVisible(true);
        
        AtualizaTabelaObjeto();
    }
    
    public void AtualizaTabelaObjeto() {
        if (codigoSelecionadoAmb != 0) {            
            TabelaBase tabela = new TabelaBase(objetoDao.SelecionarTabelaPorIdAmbiente(this.codigoSelecionadoAmb));

            tblObjeto.setModel(new DefaultTableModel(tabela.ObterDados(), tabela.ObterColuna()));                
            tblObjeto.getColumnModel().getColumn(0).setHeaderValue("Código Objeto");
            tblObjeto.getColumnModel().getColumn(1).setHeaderValue("Nome Objeto");
            tblObjeto.getColumnModel().getColumn(2).setHeaderValue("Altura");
            tblObjeto.getColumnModel().getColumn(3).setHeaderValue("Largura");            
        }
    }
        
    private void SalvarAmbiente() {
        String descricao = txtDescricao.getText();
        Ambiente ambiente = new Ambiente(this.codigoSelecionadoAmb, descricao, this.codigoSelecionadoProj);
        
        ambienteDao.Salvar(ambiente);
            
        JOptionPane.showMessageDialog(this, "Salvo com sucesso!");

        dispose();
    }
    
    private void ExcluirObjeto() {
        if (codigoSelecionadoObj != 0) {
            int opcaoSelecionada = JOptionPane.showConfirmDialog(this, "Deseja excluir esse Objeto?", "Atenção",JOptionPane.YES_NO_OPTION);
            if (opcaoSelecionada == JOptionPane.YES_OPTION) {
                objetoDao.Excluir(codigoSelecionadoObj);
                
                AtualizaTabelaObjeto();
                
                codigoSelecionadoObj = 0;                
                btnExcluirObjeto.setEnabled(false);
                btnEditarObjeto.setEnabled(false);
            }
        }
    }
}
